SQL> 
SQL> ---Show all customer and account details where the natural releationship between the two tables is based on customerid
SQL> 
SQL> select * from customers
  2  natural join accounts;

CUSTOMERID NAME                      EMAIL                     PHONE            
---------- ------------------------- ------------------------- ---------------  
ADDRESS               ACCOUNTID ACCOUNTTYPE             BALANCE                 
-------------------- ---------- -------------------- ----------                 
         1 AJAY                      ajay12@gmail.com          9234567890       
12BARAMAT ST                100 SAVING                     3200                 
                                                                                
         2 VIJAY                     vijay@gmail.com           8745328756       
NAGPUR34 BH                 101 CURRENT                 1600.87                 
                                                                                
         3 SANJAY                    sanjay76@gmail.com        7888453945       
SWARGET34 PUNE              102 CURRENT                    2100                 
                                                                                

CUSTOMERID NAME                      EMAIL                     PHONE            
---------- ------------------------- ------------------------- ---------------  
ADDRESS               ACCOUNTID ACCOUNTTYPE             BALANCE                 
-------------------- ---------- -------------------- ----------                 
         4 RAGHAV                    raghavsh21@gmail.com      8958370754       
PIMPARI PN32                103 SAVING                     4780                 
                                                                                
         5 MANISH                    manish55@gmail.com        7896507885       
VARSOLI ALIBAG21            104 SAVING                   1000.9                 
                                                                                
         6 DATTA                     datta@gmail.com           7767943590       
DADAR MUM23                 105 CURRENT                   10000                 
                                                                                

CUSTOMERID NAME                      EMAIL                     PHONE            
---------- ------------------------- ------------------------- ---------------  
ADDRESS               ACCOUNTID ACCOUNTTYPE             BALANCE                 
-------------------- ---------- -------------------- ----------                 
         7 MEDHAVI                   medhavi@gmail.com         87589123654      
BANER PU41                  106 SAVING                     1200                 
                                                                                
         8 AWANTIKA                  awantika23@gmail.com      9787321976       
BALEWADI PUNE12             107 SAVING                     7865                 
                                                                                
         9 VIRAT                     VIRATMH@GMAIL.COM         8845231167       
SATARA ST45                 108 CURRENT                    6700                 
                                                                                

CUSTOMERID NAME                      EMAIL                     PHONE            
---------- ------------------------- ------------------------- ---------------  
ADDRESS               ACCOUNTID ACCOUNTTYPE             BALANCE                 
-------------------- ---------- -------------------- ----------                 
        10 VISHAKHA                  vishakha34@gmail.com      7689554676       
DHAWADSHI ST                109 CURRENT                    2300                 
                                                                                

10 rows selected.

SQL> set pagesize 700
SQL> set linesize 700
SQL> /

CUSTOMERID NAME                      EMAIL                     PHONE           ADDRESS               ACCOUNTID ACCOUNTTYPE             BALANCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- ------------------------- ------------------------- --------------- -------------------- ---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 AJAY                      ajay12@gmail.com          9234567890      12BARAMAT ST                100 SAVING                     3200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 VIJAY                     vijay@gmail.com           8745328756      NAGPUR34 BH                 101 CURRENT                 1600.87                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 SANJAY                    sanjay76@gmail.com        7888453945      SWARGET34 PUNE              102 CURRENT                    2100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 RAGHAV                    raghavsh21@gmail.com      8958370754      PIMPARI PN32                103 SAVING                     4780                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 MANISH                    manish55@gmail.com        7896507885      VARSOLI ALIBAG21            104 SAVING                   1000.9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         6 DATTA                     datta@gmail.com           7767943590      DADAR MUM23                 105 CURRENT                   10000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         7 MEDHAVI                   medhavi@gmail.com         87589123654     BANER PU41                  106 SAVING                     1200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         8 AWANTIKA                  awantika23@gmail.com      9787321976      BALEWADI PUNE12             107 SAVING                     7865                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         9 VIRAT                     VIRATMH@GMAIL.COM         8845231167      SATARA ST45                 108 CURRENT                    6700                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        10 VISHAKHA                  vishakha34@gmail.com      7689554676      DHAWADSHI ST                109 CURRENT                    2300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

10 rows selected.

SQL> ---List all transactions and account details naturally linked by accountid
SQL> 
SQL> select * transactions
  2  natural join accounts;
select * transactions
         *
ERROR at line 1:
ORA-00923: FROM keyword not found where expected 


SQL> ed
Wrote file afiedt.buf

  1  select * from transactions
  2* natural join accounts
SQL> /

 ACCOUNTID TRANSACTIONID TDATE         AMOUNT TRANSACTIONTYPE      CUSTOMERID ACCOUNTTYPE             BALANCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
---------- ------------- --------- ---------- -------------------- ---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       100           200 01-JAN-20        200 DEPOSITE                      1 SAVING                     3200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       101           201 11-NOV-20        600 WITHDRAW                      2 CURRENT                 1600.87                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       102           202 01-SEP-20        300 DEPOSITE                      3 CURRENT                    2100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       103           203 23-AUG-20        900 DEPOSITE                      4 SAVING                     4780                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       104           204 01-DEC-25        400 WITHDRAW                      5 SAVING                   1000.9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       105           205 31-JAN-22       1100 WITHDRAW                      6 CURRENT                   10000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       106           206 01-JUN-20        200 DEPOSITE                      7 SAVING                     1200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       107           207 15-SEP-20        300 WITHDRAW                      8 SAVING                     7865                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       108           208 11-APR-21        500 DEPOSITE                      9 CURRENT                    6700                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
       109           209 21-MAR-21        300 WITHDRAW                     10 CURRENT                    2300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

10 rows selected.

SQL> ----Retrive customer names and their accounts balance using a natural join
SQL> 
SQL> select c.name,a.balance from customers c
  2  natural join accounts;
select c.name,a.balance from customers c
              *
ERROR at line 1:
ORA-00904: "A"."BALANCE": invalid identifier 


SQL> ed
Wrote file afiedt.buf

  1  select c.name,a.balance from customers c
  2* natural join accounts a
SQL> /

NAME                         BALANCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
------------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
AJAY                            3200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
VIJAY                        1600.87                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
SANJAY                          2100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
RAGHAV                          4780                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
MANISH                        1000.9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
DATTA                          10000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
MEDHAVI                         1200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
AWANTIKA                        7865                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
VIRAT                           6700                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
VISHAKHA                        2300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

10 rows selected.

SQL> ---Find customer names and transaction amounts naturally connected by account owenership.
SQL> 
SQL> select c.name,t.amount from customers c
  2  natural join accounts a
  3  natural join transaction t;
natural join transaction t
             *
ERROR at line 3:
ORA-00942: table or view does not exist 


SQL> ed
Wrote file afiedt.buf

  1  select c.name,t.amount from customers c
  2  natural join accounts a
  3* natural join transactions t
SQL> /

NAME                          AMOUNT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
------------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
AJAY                             200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
VIJAY                            600                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
SANJAY                           300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
RAGHAV                           900                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
MANISH                           400                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
DATTA                           1100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
MEDHAVI                          200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
AWANTIKA                         300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
VIRAT                            500                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
VISHAKHA                         300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

10 rows selected.

SQL> --Display all customer and transaction types naturally linked through accounts
SQL> 
SQL> select * from customers
  2  natural join accounts
  3  natural join transactions;

 ACCOUNTID CUSTOMERID NAME                      EMAIL                     PHONE           ADDRESS              ACCOUNTTYPE             BALANCE TRANSACTIONID TDATE         AMOUNT TRANSACTIONTYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
---------- ---------- ------------------------- ------------------------- --------------- -------------------- -------------------- ---------- ------------- --------- ---------- --------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
       100          1 AJAY                      ajay12@gmail.com          9234567890      12BARAMAT ST         SAVING                     3200           200 01-JAN-20        200 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       101          2 VIJAY                     vijay@gmail.com           8745328756      NAGPUR34 BH          CURRENT                 1600.87           201 11-NOV-20        600 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       102          3 SANJAY                    sanjay76@gmail.com        7888453945      SWARGET34 PUNE       CURRENT                    2100           202 01-SEP-20        300 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       103          4 RAGHAV                    raghavsh21@gmail.com      8958370754      PIMPARI PN32         SAVING                     4780           203 23-AUG-20        900 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       104          5 MANISH                    manish55@gmail.com        7896507885      VARSOLI ALIBAG21     SAVING                   1000.9           204 01-DEC-25        400 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       105          6 DATTA                     datta@gmail.com           7767943590      DADAR MUM23          CURRENT                   10000           205 31-JAN-22       1100 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       106          7 MEDHAVI                   medhavi@gmail.com         87589123654     BANER PU41           SAVING                     1200           206 01-JUN-20        200 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       107          8 AWANTIKA                  awantika23@gmail.com      9787321976      BALEWADI PUNE12      SAVING                     7865           207 15-SEP-20        300 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       108          9 VIRAT                     VIRATMH@GMAIL.COM         8845231167      SATARA ST45          CURRENT                    6700           208 11-APR-21        500 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
       109         10 VISHAKHA                  vishakha34@gmail.com      7689554676      DHAWADSHI ST         CURRENT                    2300           209 21-MAR-21        300 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

10 rows selected.

SQL> spool on
