SQL> 
SQL> select * from customers;

CUSTOMERID NAME                      EMAIL                     PHONE           ADDRESS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
---------- ------------------------- ------------------------- --------------- --------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
         1 AJAY                      ajay12@gmail.com          9234567890      12BARAMAT ST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
         2 VIJAY                     vijay@gmail.com           8745328756      NAGPUR34 BH                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 SANJAY                    sanjay76@gmail.com        7888453945      SWARGET34 PUNE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         4 RAGHAV                    raghavsh21@gmail.com      8958370754      PIMPARI PN32                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
         5 MANISH                    manish55@gmail.com        7896507885      VARSOLI ALIBAG21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
         6 DATTA                     datta@gmail.com           7767943590      DADAR MUM23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         7 MEDHAVI                   medhavi@gmail.com         87589123654     BANER PU41                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
         8 AWANTIKA                  awantika23@gmail.com      9787321976      BALEWADI PUNE12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
         9 VIRAT                     VIRATMH@GMAIL.COM         8845231167      SATARA ST45                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        10 VISHAKHA                  vishakha34@gmail.com      7689554676      DHAWADSHI ST                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

10 rows selected.

SQL> select * from accounts;

 ACCOUNTID CUSTOMERID ACCOUNTTYPE             BALANCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
---------- ---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       100          1 SAVING                     3200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       101          2 CURRENT                 1600.87                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       102          3 CURRENT                    2100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       103          4 SAVING                     4780                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       104          5 SAVING                   1000.9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       105          6 CURRENT                   10000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       106          7 SAVING                     1200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       107          8 SAVING                     7865                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       108          9 CURRENT                    6700                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
       109         10 CURRENT                    2300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

10 rows selected.

SQL> select * from TRansactions;

TRANSACTIONID  ACCOUNTID TDATE         AMOUNT TRANSACTIONTYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
------------- ---------- --------- ---------- --------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
          200        100 01-JAN-20        200 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          201        101 11-NOV-20        600 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          202        102 01-SEP-20        300 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          203        103 23-AUG-20        900 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          204        104 01-DEC-25        400 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          205        105 31-JAN-22       1100 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          206        106 01-JUN-20        200 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          207        107 15-SEP-20        300 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          208        108 11-APR-21        500 DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          209        109 21-MAR-21        300 WITHDRAW                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

10 rows selected.

SQL> ---Q.List all customers and the account types they hold, using explicit equality conditions in the join----
SQL> 
SQL> select c.customerid,c.name,c.email,c.phone,c.address,a.accounttype from customers c,accounts a
  2  where (c.customerid=a.customerid);

CUSTOMERID NAME                      EMAIL                     PHONE           ADDRESS              ACCOUNTTYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
---------- ------------------------- ------------------------- --------------- -------------------- --------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
         1 AJAY                      ajay12@gmail.com          9234567890      12BARAMAT ST         SAVING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 VIJAY                     vijay@gmail.com           8745328756      NAGPUR34 BH          CURRENT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
         3 SANJAY                    sanjay76@gmail.com        7888453945      SWARGET34 PUNE       CURRENT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
         4 RAGHAV                    raghavsh21@gmail.com      8958370754      PIMPARI PN32         SAVING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 MANISH                    manish55@gmail.com        7896507885      VARSOLI ALIBAG21     SAVING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         6 DATTA                     datta@gmail.com           7767943590      DADAR MUM23          CURRENT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
         7 MEDHAVI                   medhavi@gmail.com         87589123654     BANER PU41           SAVING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         8 AWANTIKA                  awantika23@gmail.com      9787321976      BALEWADI PUNE12      SAVING                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         9 VIRAT                     VIRATMH@GMAIL.COM         8845231167      SATARA ST45          CURRENT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        10 VISHAKHA                  vishakha34@gmail.com      7689554676      DHAWADSHI ST         CURRENT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

10 rows selected.

SQL> ----Q.Find customers who have made deposits in their checking accounts---
SQL> 
SQL> select  c.customerid,c.name,c.email,c.phone,c.address,t.transactiontype from customers c,accounts a,transactions t
  2  where (a.accountid=t.accountid) and
  3  (c.customerid=a.customerid) and t.transactiontype='DEPOSITE';

CUSTOMERID NAME                      EMAIL                     PHONE           ADDRESS              TRANSACTIONTYPE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
---------- ------------------------- ------------------------- --------------- -------------------- --------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
         1 AJAY                      ajay12@gmail.com          9234567890      12BARAMAT ST         DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
         3 SANJAY                    sanjay76@gmail.com        7888453945      SWARGET34 PUNE       DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
         4 RAGHAV                    raghavsh21@gmail.com      8958370754      PIMPARI PN32         DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
         7 MEDHAVI                   medhavi@gmail.com         87589123654     BANER PU41           DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
         9 VIRAT                     VIRATMH@GMAIL.COM         8845231167      SATARA ST45          DEPOSITE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

SQL> -----Q.Show customer and transaction details where the transaction amount is exactly equal to the account balance--
SQL> 
SQL> select  c.customerid,c.name,c.email,c.phone,c.address,a.balance,t.amount from customers c,accounts a,transactions t
  2  where  (a.accountid=t.accountid) and
  3  (c.customerid=a.customerid) and a.balance=t.amount;

no rows selected

SQL> spool on
