SQL> 
SQL> set pagesize 500
SQL> set linesize 500
SQL> ----list all customers along with their accounts and balance details
SQL> 
SQL> select c.customerid,c.name,c.email,c.phone,c.address,a.accountid,a.accounttype,a.balance from customers c
  2  inner join accounts a
  3  on(c.customerid=a.customerid);

CUSTOMERID NAME                      EMAIL                     PHONE           ADDRESS               ACCOUNTID ACCOUNTTYPE             BALANCE                                                                                                                                                                                                                                                                                                                                                                      
---------- ------------------------- ------------------------- --------------- -------------------- ---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                      
         1 AJAY                      ajay12@gmail.com          9234567890      12BARAMAT ST                100 SAVING                     3200                                                                                                                                                                                                                                                                                                                                                                      
         2 VIJAY                     vijay@gmail.com           8745328756      NAGPUR34 BH                 101 CURRENT                 1600.87                                                                                                                                                                                                                                                                                                                                                                      
         3 SANJAY                    sanjay76@gmail.com        7888453945      SWARGET34 PUNE              102 CURRENT                    2100                                                                                                                                                                                                                                                                                                                                                                      
         4 RAGHAV                    raghavsh21@gmail.com      8958370754      PIMPARI PN32                103 SAVING                     4780                                                                                                                                                                                                                                                                                                                                                                      
         5 MANISH                    manish55@gmail.com        7896507885      VARSOLI ALIBAG21            104 SAVING                   1000.9                                                                                                                                                                                                                                                                                                                                                                      
         6 DATTA                     datta@gmail.com           7767943590      DADAR MUM23                 105 CURRENT                   10000                                                                                                                                                                                                                                                                                                                                                                      
         7 MEDHAVI                   medhavi@gmail.com         87589123654     BANER PU41                  106 SAVING                     1200                                                                                                                                                                                                                                                                                                                                                                      
         8 AWANTIKA                  awantika23@gmail.com      9787321976      BALEWADI PUNE12             107 SAVING                     7865                                                                                                                                                                                                                                                                                                                                                                      
         9 VIRAT                     VIRATMH@GMAIL.COM         8845231167      SATARA ST45                 108 CURRENT                    6700                                                                                                                                                                                                                                                                                                                                                                      
        10 VISHAKHA                  vishakha34@gmail.com      7689554676      DHAWADSHI ST                109 CURRENT                    2300                                                                                                                                                                                                                                                                                                                                                                      

10 rows selected.

SQL> set pagesize 500
SQL> set pagesize 700
SQL> set linesize 700
SQL> /

CUSTOMERID NAME                      EMAIL                     PHONE           ADDRESS               ACCOUNTID ACCOUNTTYPE             BALANCE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
---------- ------------------------- ------------------------- --------------- -------------------- ---------- -------------------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         1 AJAY                      ajay12@gmail.com          9234567890      12BARAMAT ST                100 SAVING                     3200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         2 VIJAY                     vijay@gmail.com           8745328756      NAGPUR34 BH                 101 CURRENT                 1600.87                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         3 SANJAY                    sanjay76@gmail.com        7888453945      SWARGET34 PUNE              102 CURRENT                    2100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         4 RAGHAV                    raghavsh21@gmail.com      8958370754      PIMPARI PN32                103 SAVING                     4780                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         5 MANISH                    manish55@gmail.com        7896507885      VARSOLI ALIBAG21            104 SAVING                   1000.9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         6 DATTA                     datta@gmail.com           7767943590      DADAR MUM23                 105 CURRENT                   10000                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         7 MEDHAVI                   medhavi@gmail.com         87589123654     BANER PU41                  106 SAVING                     1200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         8 AWANTIKA                  awantika23@gmail.com      9787321976      BALEWADI PUNE12             107 SAVING                     7865                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
         9 VIRAT                     VIRATMH@GMAIL.COM         8845231167      SATARA ST45                 108 CURRENT                    6700                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        10 VISHAKHA                  vishakha34@gmail.com      7689554676      DHAWADSHI ST                109 CURRENT                    2300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

10 rows selected.

SQL> --Retrive all customers and their transaction history,including transaction amount and dates
SQL>  select c.customerid,c.name,c.email,c.phone,c.address,t.transactionid,t.accountid,t.tdate,t.amount from customers c
  2  inner join accounts a
  3  on(c.customer_id=a.customerid)
  4  inner join transactions t
  5  on(a.accountid=t.accountid);
on(c.customer_id=a.customerid)
   *
ERROR at line 3:
ORA-00904: "C"."CUSTOMER_ID": invalid identifier 


SQL> ed
Wrote file afiedt.buf

  1   select c.customerid,c.name,c.email,c.phone,c.address,t.transactionid,t.accountid,t.tdate,t.amount from customers c
  2  inner join accounts a
  3  on(c.customerid=a.customerid)
  4  inner join transactions t
  5* on(a.accountid=t.accountid)
SQL> /

CUSTOMERID NAME                      EMAIL                     PHONE           ADDRESS              TRANSACTIONID  ACCOUNTID TDATE         AMOUNT                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
---------- ------------------------- ------------------------- --------------- -------------------- ------------- ---------- --------- ----------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         1 AJAY                      ajay12@gmail.com          9234567890      12BARAMAT ST                   200        100 01-JAN-20        200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         2 VIJAY                     vijay@gmail.com           8745328756      NAGPUR34 BH                    201        101 11-NOV-20        600                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         3 SANJAY                    sanjay76@gmail.com        7888453945      SWARGET34 PUNE                 202        102 01-SEP-20        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         4 RAGHAV                    raghavsh21@gmail.com      8958370754      PIMPARI PN32                   203        103 23-AUG-20        900                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         5 MANISH                    manish55@gmail.com        7896507885      VARSOLI ALIBAG21               204        104 01-DEC-25        400                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         6 DATTA                     datta@gmail.com           7767943590      DADAR MUM23                    205        105 31-JAN-22       1100                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         7 MEDHAVI                   medhavi@gmail.com         87589123654     BANER PU41                     206        106 01-JUN-20        200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         8 AWANTIKA                  awantika23@gmail.com      9787321976      BALEWADI PUNE12                207        107 15-SEP-20        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
         9 VIRAT                     VIRATMH@GMAIL.COM         8845231167      SATARA ST45                    208        108 11-APR-21        500                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
        10 VISHAKHA                  vishakha34@gmail.com      7689554676      DHAWADSHI ST                   209        109 21-MAR-21        300                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

10 rows selected.

SQL> ---get details  of customers and accounts with accounts having balances above 1000 average balance
SQL> 
SQL>  select c.customerid,c.name,c.email,c.phone,c.address,a.accountid,a.accounttype,a.balance from customers c
  2  inner join accounts a
  3  on(c.customerid=a.customerid)
  4  where a.balance>(select avg(a.balance) frpm accounts where a.balance>1000);
where a.balance>(select avg(a.balance) frpm accounts where a.balance>1000)
                                            *
ERROR at line 4:
ORA-00923: FROM keyword not found where expected 


SQL> ed
Wrote file afiedt.buf

  1   select c.customerid,c.name,c.email,c.phone,c.address,a.accountid,a.accounttype,a.balance from customers c
  2  inner join accounts a
  3  on(c.customerid=a.customerid)
  4* where a.balance>(select avg(a.balance) from accounts where a.balance>1000)
SQL> /

no rows selected

SQL> spool on
